### PR TITLE
Fix unicode identifiers support

### LINKED ISSUE #184: Cl failures from clippy
https://github.com/lloydmeta/frunk/runs/2853440952

Clippy is mad because HNil implements Copy, so an inherent method `HNil::to_ref(&self) -> Self` implies a costlier operation than it actually is.  What it doesn't understand is that this method is being generated by a macro, and needs to match similar methods on other types.

Probably just want to ignore this.

### LINKED ISSUE #185: Unicode identifiers
Rust 1.53 has finally [stabilized the `non_ascii_idents` feature](https://github.com/rust-lang/rust/pull/83799)!

I do recall that frunk's type-system encoding of strings already supports unicode.  Thus it'd be interesting to look into: Does frunk already support these identifiers?  If so, we should add some regression tests.  If not, we could look into supporting them.

### PR DESCRIPTION
**Pull request by lloydmeta**
* Fixes #185  (unicode support)
* Fixes #184 (clippy warning)
  * Probably unblocks the other PR.

### CODE REVIEW

File: tests/common/mod.rs [hunk 1]
```diff
@@ -121,6 +121,7 @@ pub struct InternalUser<'a> {
     pub age: usize,
     pub address: InternalAddress<'a>,
     pub is_banned: bool,
+    pub α: bool,
```
Comment (ExpHP) [inline tests/common/mod.rs:124]: hmm, maybe try β which doesn't seem to be in the list of confusables, to avoid these warnings

**Review by ExpHP — CHANGES_REQUESTED** [review]

File: tests/common/mod.rs (hunk 1 above)
Comment (lloydmeta) [reply tests/common/mod.rs]: Good idea.

**Comment by ExpHP** [comment]
Hmmm, that unicode "mixed script confusibles" warning is really pesky. :/

Looking at this: https://www.unicode.org/Public/security/13.0.0/confusablesSummary.txt.  I guess β (beta) is no good either because it looks like ß?  I'm hard pressed to find any character that is not on here...

Maybe we should just `#![allow(mixed_script_confusables)]` on the file.  It is just a test file after all...

**Comment by lloydmeta** [comment]
Looks like あ did the trick.
